import turtle
import random
import time
colors = ["red", "blue", "green", "yellow", "orange", "purple", "pink", "brown", "gray", "cyan", "magenta", "gold", "silver"]
text="The ottomans had a sudden raid on the crusaders who were staying in this war,\n while the ottoman army was 700-800 people,\
the crusader army was 60-70 thousand people, according to a rumor,\n the Meriç river turned red from the corpses of the crusaders in the morning"
te="1371 ottoman crusader \n battle of çirmen decisive \n ottoman victory"
t=turtle.Turtle()
t.speed(100)
t.pensize(1)
turtle.bgcolor("black")
def eourupe():
    t.up()
    t.goto(random.randint(-300,300),random.randint(-300,300))
    t.down()
    t.color("red")
    t.begin_fill()
    t.circle(10)
    t.end_fill()
def hac():
    t.up()
    t.goto(random.randint(300,500),random.randint(-300,300))
    t.down()
    t.color("white")
    t.begin_fill()
    t.circle(10)
    t.end_fill()
def ottoman():
    t.color("green")
    t.begin_fill()
    for i in range(2):
        t.fd(100)
        t.left(90)
        t.fd(30)
        t.left(90)
    t.end_fill()
def one():
    for i in range(35):
        eourupe()
    t.up()
    t.goto(-300,250)
    t.down()
    ottoman()
    t.up()
    t.up()
    t.goto(-100,250)
    t.down()
    ottoman()
    t.up()
    t.goto(-300,-250)
    t.down()
    ottoman()
    t.up()
    t.up()
    t.goto(-100,-250)
    t.down()
    ottoman()
    t.up()
    t.goto(500,600)
    t.down()
    t.color("blue")
    t.begin_fill()
    for i in range(2):
        t.fd(100)
        t.right(90)
        t.fd(1200)
        t.right(90)
    t.end_fill()
def two():
    for i in range(10):
        hac()
    t.up()
    t.goto(100,100)
    t.down()
    ottoman()
    t.up()
    t.goto(100,0)
    t.down()
    ottoman()
    t.up()
    t.goto(100,-100)
    t.down()
    ottoman()
    t.up()
    t.goto(100,-200)
    t.down()
    ottoman()
    t.up()
    t.goto(500,600)
    t.down()
    t.color("blue")
    t.begin_fill()
    for i in range(2):
        t.fd(100)
        t.right(90)
        t.fd(1200)
        t.right(90)
    t.end_fill()
def three():
    turtle.bgcolor("sandybrown")
    t.up()
    t.goto(100,100)
    t.down()
    ottoman()
    t.up()
    t.goto(100,0)
    t.down()
    ottoman()
    t.up()
    t.goto(100,-100)
    t.down()
    ottoman()
    t.up()
    t.goto(100,-200)
    t.down()
    ottoman()
    t.up()
    t.goto(500,600)
    t.down()
    t.color("red")
    t.begin_fill()
    for i in range(2):
        t.fd(100)
        t.right(90)
        t.fd(1200)
        t.right(90)
    t.end_fill()
one()
time.sleep(3)
t.clear()
two()
time.sleep(3)
t.clear()
three()
time.sleep(3)
t.clear()
turtle.bgcolor("white")
t.up()
t.goto(-400,0)
t.down()
t.color(random.choice(colors))
turtle.bgcolor("black")
t.write(text, align="left", font=("Arial", 20, "bold"))
time.sleep(5)
t.clear()
turtle.bgcolor(random.choice(colors))
t.up(),t.goto(0,0),t.down()
t.write(te, align="left", font=("Arial", 40, "bold"))
turtle.done()
